name: Batch predictions

on:
  schedule:
    - cron: '* * * * *' # Run every day at midnight UTC (https://crontab.guru/#0_0_*_*_*)

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute py script
      run: python batch_predict.py
