name: Batch predictions

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC (https://crontab.guru/#0_0_*_*_*)

  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.8


    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute py script
      run: python3 batch_predict.py
